### ISSUE TITLE
errors in importing framed

### ISSUE THREAD

**Issue by hongzhonglu** [cdanielmachado/framed#35]
@cdanielmachado  I meet error when I try to use framed in my computer. Can you help me solve it?
**import carveme**
Traceback (most recent call last):
  File "/Users/luho/PycharmProjects/python learning/venv/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-12-775e13af7d85>", line 1, in <module>
    import framed
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/luho/PycharmProjects/python learning/venv/lib/python3.6/site-packages/framed/__init__.py", line 1, in <module>
    from .cobra.deletion import reaction_deletion, gene_deletion
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/luho/PycharmProjects/python learning/venv/lib/python3.6/site-packages/framed/cobra/deletion.py", line 7, in <module>
    from simulation import FBA, pFBA, MOMA, lMOMA, ROOM
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'simulation'

**Comment by cdanielmachado** [comment]
Hi @hongzhonglu 

I can see you are using python 3.6. The latest stable release of framed doesn't yet support python 3.

You can install the latest official release for python 2.7 using pip, or you can install framed in python 3 from our py3 development branch.

**Comment by hongzhonglu** [comment]
@cdanielmachado Great thanks!
